app = "ciso-assistant"

[build]
  builder = "dockerfile"
  builder = "./backend/Dockerfile"

[env]
  DEBUG = "False"
  ALLOWED_HOSTS = "*"
  DISABLE_COLLECTSTATIC = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443