app = "saas-dqokpw"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python", "gcr.io/paketo-buildpacks/nodejs"]
  build = "."
  BP_OCI_DOCUMENTATION = "https://github.com/CISO-Assistant/CISO-Assistant"
  BP_OCI_CREATED = "now"
  BP_NODE_PROJECT_PATH = "frontend"

[env]
  DEBUG = "False"
  ALLOWED_HOSTS = "*"
  DISABLE_COLLECTSTATIC = "1"
  BP_NODE_PROJECT_PATH = "frontend"
  BP_NODE_PACKAGE_MANAGER = "pnpm"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443