[phases.setup]
nix_pkgs = ["python310", "nodejs-18_x"]

[phases.build]
commands = [
    "cd backend && poetry install --no-interaction --no-ansi",
    "cd frontend && npm install && npm run build"
]

[phases.start]
command = "cd backend && python manage.py migrate && gunicorn ciso_assistant.wsgi --workers 4 --timeout 120 --bind 0.0.0.0:$PORT"